#!/bin/sh

#===============================================================================
# System
#===============================================================================

mkdir -p /proc /sys /tmp /var/run
# Mount fstab
mount -a

# Create all the symlinks to /bin/busybox
busybox --install -s

# Create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

# Set hostname
hostname "kdev"

# modprobe
/etc/init.d/kmod
# networking
/etc/init.d/network
