#!/bin/sh

#===============================================================================
# System
#===============================================================================

mkdir -p /proc /sys /tmp /var/run /var/log /dev/pts
# Mount fstab
mount -a

# Create all the symlinks to /bin/busybox
busybox --install -s

# Fix up permissions for /root
chmod -R 600 /root

# Create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

syslogd -O /var/log/syslog

dropbear -R -s -g -B

# modprobe
/etc/init.d/kmod
# networking
/etc/init.d/network
